name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cargo test
        run: cargo test

  msrv-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Install cargo-minimal-versions
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack,cargo-minimal-versions

      - name: Install MSRV toolchain
        run: rustup toolchain install 1.65

      - name: Run Cargo test on MSRV
        run: cargo +1.65 minimal-versions test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cargo clippy
        run: cargo clippy -- --deny warnings

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nightly toolchain
        run: rustup toolchain install nightly

      - name: Install Nightly rustfmt
        run: rustup component add --toolchain nightly rustfmt

      - name: Run cargo format
        run: cargo +nightly fmt --check

  no-alloc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install no-std/no-alloc target
        run: rustup target add x86_64-unknown-none

      - name: Check build on no-std/no-alloc target
        run: cargo build --target x86_64-unknown-none --no-default-features
